### ISSUE TITLE
invalid documentation

### ISSUE THREAD

**Issue by joerghenkebuero** [neelsoumya/dsSurvival#18]
The installation of Datashield packages does not fit to the current OPAL version

Try to install this R package in a current OPAL (version 4.4.10)

**Expected behavior**
The documentation of this package does not fit to the dialogs from OPAL; see screenshots of the current forms

**Screenshots**
![grafik](https://user-images.githubusercontent.com/69628891/188838578-99dc00d6-4366-45be-b51a-652e4b08fa96.png)
![grafik](https://user-images.githubusercontent.com/69628891/188838600-aa7bb5ec-d039-4e4b-99d5-32312c673312.png)

**Desktop (please complete the following information):**
does not matter

**Smartphone (please complete the following information):**
does not matter

**Additional context**
Please update the installation procedures or create multiple versions if you want to keep the old versions, too

**Comment by neelsoumya** [comment]
thank you @joerghenkebuero ! this is now fixed.
