### ISSUE TITLE
listDisclosureSettingsDS() duplicated from dsBase

### ISSUE THREAD

**Issue by tombisho** [neelsoumya/dsSurvival#19]
**Describe the bug**
listDisclosureSettingsDS() is duplicated from dsBase. Given that this package imports dsBase, listDisclosureSettingsDS() should be used from there

**To Reproduce**
1. Load dsBase library
2. Load dsSurvival library

dsomics_testing-rserver-1    | Attaching package: ‘dsSurvival’
dsomics_testing-rserver-1    |
dsomics_testing-rserver-1    | The following object is masked from ‘package:dsBase’:
dsomics_testing-rserver-1    |
dsomics_testing-rserver-1    |     listDisclosureSettingsDS

**Expected behavior**
No message about duplicated functions

**Comment by neelsoumya** [comment]
fixed in latest release by @StuartWheater
