### ISSUE TITLE
ds.cox.zphSLMA(fit = 'coxph_serverside') hangs

### ISSUE THREAD

**Issue by AlanRace** [neelsoumya/dsSurvival#7]
Calling `ds.cox.zphSLMA(fit = 'coxph_serverside')` doesn't appear to work. I get the following message, but it just stays at this point without progressing:

```r
Getting aggregate Study1 (cox.zphSLMADS("coxph_serverside", "km", TRUE, FALSE, TRUE)) []  25% ...
```

`ds.coxphSummary(x = 'coxph_serverside')` works fine, so I know the variable is at least on the server. Is there a way to debug what is happening?

**Comment by neelsoumya** [comment]
what dataset are you trying it on? could you please post or give a link to your complete code (and your data is possible)

**Comment by AlanRace** [comment]
I can't provide the data as it is real clinical data, but the relevant code bits are (names changed, but code remains the same):

```r
ds.coxphSLMAassign(surv_object ~ age + sex + lab_value + risk_factor, dataName = "dataset", 
                   objectname = 'coxph_serverside')

ds.cox.zphSLMA(fit = 'coxph_serverside')
```

`ds.coxph.SLMA` also works fine, so I can't imagine it's a problem with the data.

**Comment by neelsoumya** [comment]
you can try with a smaller subset of your data

**Comment by neelsoumya** [comment]
you can also look at the memory footprint of your server
